### ISSUE TITLE
Fix installation of MT4 via xdotool

### ISSUE THREAD

**Issue by kenorb** [EA31337/FX-MT-VM#113]
Branch: `m4x`
File: `scripts/install_mt4-xdot.sh`

### Problem

The installation of MT4 platform fails on _Travis CI_ due to network issues. See build: [330587688](https://travis-ci.org/EA31337/FX-MT-VM/builds/330587688).

Error:

> Please specify,Server:,Login:,Password:

Possibly related to outdated `libgnutls` binary, see: GH-70, GH-105, a569b2d (I've tried to re-apply but it didn't work), but it could be also some SSL, firewall, proxy issue, or missing some Wine library.

**Comment by ryu0** [comment]
I'll take a look at this one too. Thanks for the tip.

**Comment by kenorb** [comment]
Send the PR so I’ll check the hang, if it bypass the proxy issue and multiple restart will finish the installer, that should be good for now.

**Comment by ryu0** [comment]
Ok. I haven't found a way to actually script the restarts yet. Is that something you're intending to resolve?

**Comment by kenorb** [comment]
Fixed in #121

**Comment by kenorb** [comment]
@ryu0 Could you also test the other 2 similar scripts using `.verb` files? See: #122 (see [bounty](https://www.bountysource.com/issues/58861057-fix-mt4-and-mt5-installation)). They were working before, so I hope you won't get any bigger troubles. I'll back in the evening.
