### ISSUE TITLE
MT4 doesn't install.

### ISSUE THREAD

**Issue by kenorb** [EA31337/FX-MT-VM#40]
MT4 seems to doesn't install anymore (see build [104776373](https://travis-ci.org/EA31337/FX-MT-VM/jobs/104776373)).

The same for the build which was previously working, see: [103991713](https://travis-ci.org/EA31337/FX-MT-VM/jobs/103991713).

**Comment by d-a-t-a-d-i-t** [comment]
Probably some key sequences have changed in the latest installer, will check it today.

**Comment by kenorb** [comment]
Fixed in a569b2d9a5425c91d3f8c9f937e335d123d303d9
