### ISSUE TITLE
Write script to install MT5 via winetricks

### ISSUE THREAD

**Issue by kenorb** [EA31337/FX-MT-VM#49]
There is existing script which installs MT4 platform (`install_mt4.sh`).

The goal is to write new script to install [MT5 platform](http://www.metatrader5.com/en/download) ([exe file](https://download.mql5.com/cdn/web/metaquotes.software.corp/mt5/mt5setup.exe)).

Please check `install_mt.sh` (same script can be reused) as initial example which aims to load [winetricks](https://github.com/Winetricks/winetricks/blob/master/src/winetricks) (it's assumed it's already installed) in order to load the necessary functions. Then use `w_ahk_do` function and other provided by winetricks to install the binary.

Here is example of installing [Meta Trader 4 using winetricks](https://github.com/Winetricks/winetricks/commit/774a45b6fd22d8b6ea1384144f11b2a1698ee69c), so it should be fairly similar. Use the latest version of wine. Check also this [page](https://appdb.winehq.org/objectManager.php?sClass=version&iId=19984) for any compatibility issues or bugs.

**Comment by lu43n** [comment]
#55

**Comment by kenorb** [comment]
Fixed.
